### ISSUE TITLE
JS-Controller 3.3 - wrong type "number" but has to be "string"

### ISSUE THREAD

**Issue by TheBrain26** [ruhr70/ioBroker.fritzbox#37]
fritzbox.0 warn	State value to set for "fritzbox.0.calls.counterActualCalls.connectCount" has wrong type "number" but has to be "string"
fritzbox.0 warn	State value to set for "fritzbox.0.calls.counterActualCalls.ringCount" has wrong type "number" but has to be "string"
fritzbox.0 warn	State value to set for "fritzbox.0.system.deltaTime" has wrong type "number" but has to be "string"

ioBroker/ioBroker.js-controller#1299

**Comment by Feuer-sturm** [comment]
@Apollon77 can you please have a look on this issue as well?

**Comment by Apollon77** [comment]
siehe PR, alternativ mein PR

**Comment by Feuer-sturm** [comment]
@Apollon77 @ruhr70 

Ich hab gerade die Version von github installiert.

Es sind noch folgende Meldungen vorhanden

```
20 Jul 2021 19:37:10.581
fritzbox.0 (16849) State value to set for "fritzbox.0.calls.missedCount" has to be type "string" but received type "number"
20 Jul 2021 19:37:10.579
fritzbox.0 (16849) State value to set for "fritzbox.0.calls.counterActualCalls.allActiveCount" has to be type "string" but received type "number"
20 Jul 2021 19:37:10.576
fritzbox.0 (16849) State value to set for "fritzbox.0.calls.connectNumbers" has to be type "string" but received type "object"
20 Jul 2021 19:37:10.573
fritzbox.0 (16849) State value to set for "fritzbox.0.calls.ringActualNumbers" has to be type "string" but received type "object"
20 Jul 2021 19:37:10.564
fritzbox.0 (16849) State value to set for "fritzbox.0.wlan.enabled" has to be type "boolean" but received type "string" 
```

**Comment by Apollon77** [comment]
@Feuer-sturm Bitte lösch mal die betroffenen Objekte und starte Adapter neu ... kommen die Meldungen dann wieder?

**Comment by Feuer-sturm** [comment]
@Apollon77 Ja die Meldungen kommen, wenn ich zuvor alle Objekte unter fritzbox.* lösche und dann die Instanz neu starte.

**Comment by Apollon77** [comment]
Ok, neuer PR ... oder mein Fork

@ruhr70 nohcmal neu für dich :-))

**Comment by Feuer-sturm** [comment]
@Apollon77 Ich hab gerade mal deinen Fork (https://github.com/Apollon77/ioBroker.fritzbox) installiert aber die folgenden Meldungen tauche noch auf. Die Datenpunkte habe ich zuvor komplett gelöscht.

```
20 Jul 2021 23:45:35.624
fritzbox.0 (18906) State value to set for "fritzbox.0.calls.counterActualCalls.allActiveCount" has to be type "string" but received type "number"
20 Jul 2021 23:45:35.620
fritzbox.0 (18906) State value to set for "fritzbox.0.calls.connectNumbers" has to be type "number" but received type "object"
20 Jul 2021 23:45:35.608
fritzbox.0 (18906) State value to set for "fritzbox.0.calls.ringActualNumbers" has to be type "number" but received type "object" 
```

**Comment by Apollon77** [comment]
Ok, they were new ... fixed in my fork/PR

**Comment by Feuer-sturm** [comment]
Thanks. With your new fork everything looks good now.

**Comment by Khaos66** [comment]
@Apollon77 Thank you for your fork! The original adapter (this repo) doesn't work anymore =(
